name: Package and Release
on:
  push:
    branches:
      - "master"

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: "22"
      - name: Install Dependencies
        run: pnpm install
      - name: Package
        run: pnpm run package
      - name: Publish
        run: pnpm run publish
        env:
          VSCE_PAT: ${{ secrets.AZURE_TOKEN }}
